version: "3.3"
services:
  database:
    image: postgres # use latest official postgres version
    container_name: postgres
    ports:
      - 5432:5432
      - 5000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bar
#    volumes:
#      - db:/var/lib/postgresql/data/ # persist data even if container shuts down
  webserver:
    build: .
    container_name: webserver
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=postgres
    depends_on:
      - database
    command: sh -c "migrate db init && migrate db migrate && migrate db upgrade"
volumes:
  db:
