"""empty message

Revision ID: b7cc63348271
Revises: 
Create Date: 2020-07-10 22:45:15.043265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cc63348271'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sf_county', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('alameda_county', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('san_mateo_county', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('contra_costa_county', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('santa_clara_county', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('county', sa.Enum('all', 'some', 'unknown', name='countyenum'), nullable=True),
    sa.Column('category', sa.Enum('agriculture', 'all', 'unknown', 'multiple', 'healthcare', 'entertainment', 'hospitality', 'manufacturing', 'education', 'mass_media', 'software', 'real_estate', 'sport', 'transport', 'financial_services', name='categoryenum'), nullable=True),
    sa.Column('black_owned', sa.Enum('Yes', 'No', name='binary'), nullable=True),
    sa.Column('lgbtq', sa.Enum('Yes', 'No', name='binary'), nullable=True),
    sa.Column('women_owned', sa.Enum('Yes', 'No', name='binary'), nullable=True),
    sa.Column('non_profit', sa.Enum('all', 'unknown', 'non_profits_only', 'businesses_only', name='nonprofitenum'), nullable=True),
    sa.Column('_100_or_fewer', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('_500_or_fewer', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('_750_or_fewer', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('_750_more', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('relief_type', sa.Enum('covid', 'protest_damage', 'both', name='relieftypeenum'), nullable=True),
    sa.Column('award_type', sa.Enum('recurring', 'one_time', name='awardtypeenum'), nullable=True),
    sa.Column('award_amount_specified', sa.Enum('Yes', 'No', name='binary'), nullable=True),
    sa.Column('max_award_amount', sa.Integer(), nullable=True),
    sa.Column('interest_rate_applicable', sa.Enum('yes_and_reported', 'yes_but_not_reported', 'no', 'unknown', name='interestrateapplicableenum'), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('support_type', sa.Enum('insurance', 'loan', 'grant', name='supporttypeenum'), nullable=True),
    sa.Column('sector_type', sa.Enum('public', 'private', name='sectortype'), nullable=True),
    sa.Column('supported_entity', sa.Enum('government', 'non_profit', 'gofund_me', 'private', name='supportedentity'), nullable=True),
    sa.Column('entity_name', sa.Text(), nullable=True),
    sa.Column('deadline_applicable', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('english', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('chinese', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.Column('spanish', sa.Enum('Yes', 'No', 'Unknown', name='binarywithunknown'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relief')
    # ### end Alembic commands ###
